### ISSUE TITLE
Filtering based on labels

### ISSUE THREAD

**Issue by ssozonoff** [teralytics/prometheus-ecs-discovery#9]
Any chance to add the ability to filter based on a label. The problem is that my prometheus endpoints are not always the same so I would need to have separate jobs using seperate sd files generated using this script.

**Comment by chicofranchico** [comment]
Right now, if your ECS container has the `PROMETHEUS_EXPORTER_PORT` label it will match that. The documentation should probably mention that.

**Comment by ssozonoff** [comment]
Agreed I saw that in the source code. However how can I limit the set of results returned since they dont all share the same prometheus endpoint URL ?

**Comment by chicofranchico** [comment]
Unfortunately, it's only possible to do it for all. This could be an enhancement to filter by either a tag, another label or even a group of ECS clusters.

**Comment by ssozonoff** [comment]
Or even simply by Service :-)

**Comment by ssozonoff** [comment]
I am not GO programmer but I did take a stab at this based on a services filter. Happy to do a push request

**Comment by angulito** [comment]
I think maybe this example helps you:

```
  - job_name: ecsdiscovery

    file_sd_configs:
      - files:
        - ecs_file_sd.yml
        refresh_interval: 10m

    relabel_configs:
      # filter all the targets whose task_name label matches with the regex
      - source_labels: [task_name]
        regex: 'mytask-.*'
        action: keep
```

So, although the file `ecs_file_sd.yml` contains a bunch of tasks, the prometheus job will only get the tasks with task_name ~ /mytask-.*/
